# Generated by Django 5.2.12 on 2026-04-08 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
