# Generated by Django 5.2.12 on 2026-04-29 06:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_addcart'),
        ('image', '0004_alter_products_count_alter_products_currentprice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addcart',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='image.products'),
        ),
        migrations.AlterField(
            model_name='addcart',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='blog.user'),
        ),
    ]
