# Generated by Django 5.2.12 on 2026-04-13 05:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0002_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productimage', models.ImageField(blank=True, null=True, upload_to='image/')),
                ('productname', models.CharField(max_length=100)),
                ('currentprice', models.IntegerField(max_length=100)),
                ('previousprice', models.IntegerField(max_length=100)),
                ('descripe', models.CharField(max_length=300)),
                ('count', models.IntegerField(max_length=100)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorie', to='image.img')),
            ],
        ),
        migrations.DeleteModel(
            name='product',
        ),
    ]
