# Generated by Django 5.2.12 on 2026-04-17 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0003_products_delete_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='count',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='products',
            name='currentprice',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='products',
            name='previousprice',
            field=models.IntegerField(),
        ),
    ]
